openapi: 3.0.0
info:
  title: Shop API
  description: API documentation for Shop_BE
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

paths:
  /access/signup:
    post:
      summary: Sign up a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "testuser"
        password:
          type: string
          example: "123456"

    SignupResponse:
      type: object
      properties:
        message:
          type: string
          example: "User created successfully"
        userId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request data"
